version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-irtzex8v7x2f"
s3_prefix = "sam-app-1"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=463626065242.dkr.ecr.ap-northeast-1.amazonaws.com/samapp18d79e69b/helloworldfunction19d43fc4repo"]
